import time
print(" (0)")
print(" TT ")
print(" LL")
print("\n")
time.sleep(0.15)
print("  (0)")
print("  TT ")
print("  LL")
print("\n")
time.sleep(0.15)
print("   (0)")
print("   TT ")
print("   LL")
print("\n")
time.sleep(0.15)
print("    (0)")
print("    TT ")
print("    LL")
print("\n")
time.sleep(0.15)
print("     (0)")
print("     TT ")
print("     LL")
print("\n")
time.sleep(0.15)
print("      (0)")
print("      TT ")
print("      LL")
print("\n")
#
#
time.sleep(0.15)
print("     \(0)/")
print("      TT ")
print("      LL")
print("\n")
time.sleep(0.15)
print("      []")
print("\n")
print("\n")
print("\n")
print("\n")
print("     \(0)/")
print("      TT ")
print("      LL")
print("\n")
time.sleep(0.15)
print("      []")
print("\n")
print("\n")
print("\n")
print("     \(0)/")
print("      TT ")
print("      LL")
print("\n")
time.sleep(0.15)
print("      []")
print("\n")
print("\n")
print("     \(0)/")
print("      TT ")
print("      LL")
print("\n")
time.sleep(0.15)
print("      []")
print("\n")
print("     \(0)/")
print("      TT ")
print("      LL")
print("\n")
time.sleep(0.15)
print("      []")
print("     \(0)/")
print("      TT ")
print("      LL")
print("\n")
time.sleep(0.15)
print("      []")
print("    \(::)/")
print("      TT ")
print("      LL")
print("\n")
time.sleep(0.15)
print("      []")
print("    \::::/")
print("      TT ")
print("      LL")
print("\n")
time.sleep(0.15)
print("      []")
print("    ::::::")
print("      TT ")
print("      LL")
print("\n")
time.sleep(0.15)
print("    ::[]::")
print("      TT ")
print("      LL")
print("\n")
time.sleep(0.15)
print("    :[  ]:")
print("      TT ")
print("      LL")
print("\n")
time.sleep(0.15)
print("    [    ]")
print("      TT ")
print("      LL")
print("\n")
time.sleep(0.15)
print("     [  ]")
print("      TT ")
print("      LL")
print("\n")
time.sleep(0.15)
print("      []")
print("      TT ")
print("      LL")
print("\n")
time.sleep(0.15)
print("      []")
print("\n")
print("      TT ")
print("      LL")
print("\n")
time.sleep(0.15)
print("      []")
print("      \/")
print("      TT ")
print("      LL")
print("\n")
time.sleep(0.15)
print("      []")
print("      \/ ")
print("      LL")
print("\n")
time.sleep(0.15)
print("      [] ")
print("      \/")
print("\n")
time.sleep(0.15)
print("      [] ")
print("\n")
time.sleep(0.15)
print("      [🐄] ")
print("\n")
print("\n")
time.sleep(0.15)
print("     [🐄] ")
print("\n")
print("\n")
time.sleep(0.15)
print("    [🐄] ")
print("\n")
print("\n")
time.sleep(0.15)
print("   [🐄] ")
print("\n")
print("\n")
time.sleep(0.15)
print("  [🐄] ")
print("\n")
print("\n")
time.sleep(0.15)
print(" [🐄] ")
print("\n")
print("\n")
time.sleep(0.15)
print("[🐄] ")
print("\n")
print("\n")
time.sleep(0.15)
print("[🐄] ")
print("\n")
print("\n")
time.sleep(0.15)
print("🐄] ")
print("\n")
print("\n")
time.sleep(0.15)
print("] ")
print("\n")
print("\n")
time.sleep(0.15)
print(" ")
print("\n")
print("\n")
time.sleep(0.15)
print("/\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("     0")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("     0")
print("        ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     /l\  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     -l-  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     \l/  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     -l-  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     /l\  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     /l\  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     -l-  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     \l/  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     -l-  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     /l\  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     /l\  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     -l-  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     \l/  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     -l-  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     /l\  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     /l\  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     -l-  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     \l/  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     -l-  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     /l\  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("   0")
print("  /l\  ")
print("  /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("0")
print("/l\  ")
print("/\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("   0")
print("  /l\  ")
print("  /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     /l\  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("   0")
print("  /l\  ")
print("  /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("0")
print("/l\  ")
print("/\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("   0")
print("  /l\  ")
print("  /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     /l\  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("   0")
print("  /l\  ")
print("  /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("0")
print("/l\  ")
print("/\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("   0")
print("  /l\  ")
print("  /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     /l\  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("   0")
print("  /l\  ")
print("  /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("0")
print("/l\  ")
print("/\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("   0")
print("  /l\  ")
print("  /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      0")
print("     /l\  ")
print("     /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("   0")
print("  /l\  ")
print("  /\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("0")
print("/l\  ")
print("/\ ")
print("\n")
print("\n")
time.sleep(0.15)
print("      []")
print("     \(0)/")
print("      TT ")
print("      LL")
print("\n")